create table
  public.ideas (
    id bigint generated by default as identity,
    created_at timestamp with time zone not null default now(),
    description text not null,
    id_user uuid not null default auth.uid (),
    constraint ideas_pkey primary key (id)
  ) tablespace pg_default;